/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <opencv2/opencv.hpp>

using namespace cv;
/* Header for class com_example_msalm_facedetection_OpencvClass */

#ifndef _Included_com_example_msalm_facedetection_OpencvClass
#define _Included_com_example_msalm_facedetection_OpencvClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_msalm_facedetection_OpencvClass
 * Method:    faceDetection
 * Signature: (J)V
 */
 void detect(Mat& frame);

JNIEXPORT void JNICALL Java_com_example_msalm_facedetection_OpencvClass_faceDetection
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
